### PR TITLE
fix: support for block devices

### PR DESCRIPTION
**Pull request by michaeladler**
Currently it's not possible to edit devices (e.g. /dev/sda1) since a new file is created and then moved to its destination.

### CODE REVIEW

**Comment by itchyny** [comment]
This is an intended implementation. Currently the bed command continues to read the original file contents, so the writing command must create a new file. Try deleting single byte at the head to see what happens on writing. Also the bed command sometimes deals with a large file contents and may crash while writing, so the original file may corrupt without atomic write.

**Comment by michaeladler** [comment]
Ah I see, yeah, if an edit can result in a different file size that's an issue (I only changed some bytes thus I didn't notice). But if the file size remains the same you could only `seek` and `write` the modified bytes which for large files or devices would be faster anyway. So how about this: if the file size remains the same, only write the changed bytes (so we need to keep track of it) otherwise you the `write` and `rename` approach. Would you see a problem with that?

**Comment by michaeladler** [comment]
Yeah I tend to agree, it will require quite some effort to implement this. Meanwhile I found hecate which only needed minor patching since it already uses mmap under the hood to edit device partitions (which has issues with undo of course but is good enough for my use-case). Closing this merge request since it needs more clarification upfront. If someone else wants to take this up, feel free, I won't have time for this in the foreseeable future.

**Comment by itchyny** [comment]
I have an attempt to fix the issue with the following patch. Can you test it?
```diff
diff --git a/window/manager.go b/window/manager.go
index 4e3866c..965bcc6 100644
--- a/window/manager.go
+++ b/window/manager.go
@@ -553,6 +553,24 @@ func (m *Manager) writeFile(r *event.Range, name string) (string, int64, error)
 		window.name = filepath.Base(name)
 		window.mu.Unlock()
 	}
+	if fi, err := os.Lstat(name); err == nil && fi.Mode()&os.ModeType == os.ModeDevice {
+		f, err := os.OpenFile(name, os.O_RDWR, 0)
+		if err != nil {
+			return name, 0, err
+		}
+		defer f.Close()
+		if err := f.Truncate(0); err != nil {
+			return name, 0, err
+		}
+		n, err := window.writeTo(r, f)
+		if err != nil {
+			return name, 0, err
+		}
+		if window.filename == name {
+			window.savedChangedTick = window.changedTick
+		}
+		return name, n, nil
+	}
 	tmpf, err := os.OpenFile(
 		name+"-"+strconv.FormatUint(rand.Uint64(), 16),
 		os.O_RDWR|os.O_CREATE|os.O_EXCL, m.filePerm(name),
```

**Comment by michaeladler** [comment]
Hi,

your patch doesn't work since `f.Truncate(0)` doesn't work for devices (see man(2) ftruncate):

```
truncate /dev/loop0p1: invalid argument
```

Just omit the `Truncate` and check that the file size doesn't change (think about device partitions: you must not modify
their bounds!).

Kind Regards,
  Michael

**Pull request closed without merging**
