### PR TITLE
Make Page Up / Down jump size relative

### PR DESCRIPTION
**Pull request by ilius**
Change Page Up / Down jump size from `height - 2` to `height * 0.95`

### CODE REVIEW

**Comment by itchyny** [comment]
The implementations originate from Vim implementation, for example [here](https://github.com/vim/vim/blob/v9.0.0000/src/move.c#L2469). Is there any relational reason to change the behavior?

**Comment by ilius** [comment]
The terminal size can change just like display size (pixels). It's best to make things scalable, and be more compatible with different environments. There is nothing special about "2 rows". Even the ratio 0.9 or %90 can be configurable.

**Comment by ilius** [comment]
Why do you think they subtract 2?
Because we don't want the entire page disappear.
We want to see a bit of last page and follow where we left off.

But we might be using a very tall window or very wide window for different use cases. So it's best to keep about a certain percentage of current page text, which means a percentage of hight.

**Comment by itchyny** [comment]
Even if I tried using bed with very tall window over 120 characters, I'm not convinced that using ratio than fixed rows is better default. While using <kbd>C-f</kbd>, I want to scroll as much as possible, but need over-wrapping rows and 2 for that reason is predictable regardless of the window height. If there isn't other good reason changing the behavior, I'm closing this PR.

**Comment by ilius** [comment]
What about a very wide window? Like 120 columns and 10 rows.

You asked for a logical reason and I think I gave one.
You can close it if you don't like changing your habbit.

**Comment by itchyny** [comment]
I don't think window width is related to how pages are scrolled down. By the way, I noticed that width is limited to 32 bytes but I'll increase this limitation later.

**Pull request closed without merging**
